#cong ket noi
spring.datasource.url=jdbc:postgresql://ep-long-rain-a1mba3uv.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.url=jdbc:postgresql://localhost:5432/doancoso2 #link local
#Ten acc va mat khau
#spring.datasource.username=postgres
#spring.datasource.password=1234

#tai khoan va mat khau database
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iXoC42HxOnWI
# cho phep java tuong tac vs postgre
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#tu dong cap nhat database du tren code
spring.jpa.hibernate.ddl-auto=update
#show lenh sql
logging.level.org.hibernate.SQL=DEBUG
#hien thi cac gia tri cu the duoc truyeng vao ?
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#google.client.id=828242487789-q47gae0v5gdi0b310rvtp1i590ds0g3s.apps.googleusercontent.com #google(tam thoi chua code, code sau)
jwt.secret=TGVhcm52ZXJzZSwg4bupbmcgZOG7pW5nIGjhu41jIHThuq1wIGTDoG5oIGNobCBzaW5oIHZpw6puIHjhu4xuIG5o4bqldCBo4buHIG3hurd0IHRy4budaQ0K
#Learnverse, ung dung hoc tap danh cho sinh vien xin nhat he mat troi


# === Cau Hinh server ===
#payos
PAYOS_CLIENT_ID= 0b9e0232-5046-4c8b-90cd-caeab2b3c5ab
PAYOS_API_KEY= a982d6d7-9c26-4023-bd35-03e51707d391
PAYOS_CHECKSUM_KEY= 2b5df7616cc841b3ab09c4357ab905770892361819f0eede2a527e8a50832847
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
#port fe
BASE_URL_FE = http://localhost:5173
payos.return-url=${BASE_URL_FE}/payment-success
payos.cancel-url=${BASE_URL_FE}/courses
#gemini
gemini.api.key=${GEMINI_API_KEY:AIzaSyCW15Mf0mBlh9OUSMvZv9195kHdGg4fBIA}

# === FILE UPLOAD CONFIGURATION ===
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# === CLOUDINARY CONFIGURATION ===
cloudinary.cloud-name=de9v1oqbq
cloudinary.api-key=${CLOUDINARY_API_KEY:254212915653933}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:QlPMpXC3S8b2NWxwcxF9Tp5WRDw}

# === UPLOAD TEMP DIRECTORY ===
app.upload.temp-dir=./temp-uploads

# === MAIL CONFIGURATION ===
MAIL_USERNAME=clonevclone05@gmail.com
MAIL_PASSWORD=tuoq exbv wjhi pbfc
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true